{{- range .Values.redirects }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .host }}"
  labels:
    app: {{ printf "%s-pod" .host }}
spec:
  selector:
    matchLabels:
      app: {{ printf "%s-pod" .host }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-pod" .host }}
    spec:
      containers:
        - name: {{ printf "%s-pod" .host }}
          image: {{ .image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .port }}
---
{{- end }}
