{{- range .Values.redirects }}
{{- $base := printf "%s-redirect-%s" $.Release.Name .name }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $base }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: '{{ .issuer }}'
    traefik.ingress.kubernetes.io/router.entrypoints: {{ join "," $.Values.entryPoints }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ printf "%s-redirect-%s" $.Release.Name .name }}
spec:
  ingressClassName: {{ $.Values.ingressClassName }}
  tls:
    - hosts:
        - {{ .host }}
      secretName: {{ default (printf "%s-redirect-%s-tls" $.Release.Name .name) .tlsSecretName }}
  rules:
    - host: '{{ .host }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  {{ $base }}
                port:
                  number: {{ .port }}
---
{{- end }}
