{{- range .Values.redirects }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .host | replace "." "-" }}"
  annotations:
    cert-manager.io/cluster-issuer: '{{ .issuer }}'
    traefik.ingress.kubernetes.io/router.entrypoints: {{ join "," $.Values.entryPoints }}
    traefik.ingress.kubernetes.io/router.middlewares: "{{ $.Release.Namespace }}-{{ .host | replace "." "-" }}@kubernetescrd"
spec:
  {{- with $.Values.ingressClassName }}
  ingressClassName: {{ . | quote }}
  {{- end }}
  tls:
    - secretName: {{ (default (printf "%s-tls" (.host | replace "." "-")) .tlsSecretName) | quote }}
      hosts:
        - {{ .host }}
  rules:
    - host: '{{ .host }}'
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  "{{ .host | replace "." "-" }}"
                port:
                  number: {{ .port }}
---
{{- end }}
