{{- range .Values.redirects }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ .host }}"
spec:
  selector:
    app: {{ printf "%s-pod" .host }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ .port }}
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
---
{{- end }}
