{{- range .Values.redirects }}
{{- $base := printf "%s" (replace .host "." "-") }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ $base }}"
spec:
  selector:
    app: {{ printf "%s-pod" $base }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ .port }}
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
---
{{- end }}
