{{- range .Values.redirects }}
{{- $base := printf "%s-redirect-%s" $.Release.Name .name }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $base }}
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: {{ printf "%s-pod" $base }}
  type: ClusterIP
  ports:
    - name: http
      port: {{ .port }}
      targetPort: {{ .port }}
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
---
{{- end }}
